/* This file was auto-generated by
   gen_chartab */

#ifndef PARSEGEN_CHARTAB_HPP
#define PARSEGEN_CHARTAB_HPP

namespace parsegen {

enum { NCHARS = 98 };

#define PARSEGEN_CHARTAB_SIZE 128
extern int const chartab[PARSEGEN_CHARTAB_SIZE];
extern char const inv_chartab[NCHARS];

}  // end namespace parsegen

#endif
